### ISSUE TITLE
[Feature Request] reset validators

### ISSUE THREAD

**Issue by south-pacific** [semisleep/simple-vue-validator#11]
嗨，你好。
在使用的时候有些场景需要设置validators，例如表单是异步拉取渲染的，就是说在mounted之后的ajax请求才获取表单有什么字段。
是不是能够提供设置或者重置validators的功能呢？
我看了下mixin.js里面的代码，vm.$options.validators是用作初始化的，不知道提供一个resetValidators方法是否可行？

**Comment by semisleep** [comment]
@south-pacific 你好，我更新了代码，你可以使用this.$setValidators(validators)来设置。麻烦你测试一下，然后看看有没有什么问题？因为我这边没有代码可以测试你说的case。
谢谢！
