### ISSUE TITLE
How to validate in vuex actions ?

### ISSUE THREAD

**Issue by lyquocnam** [semisleep/simple-vue-validator#14]
Hi author, i use vuex and my save action in $store of vuex, so how to validate in vuex actions ?

**Comment by DeroSavage** [comment]
You dont. You validate in the component and call the vuex action only if everythings fine. Like this:
`this.$validate().then((success) => {
          if (success) {
               // Call Action
          }
})
`

**Comment by lyquocnam** [comment]
thanks @DeroSavage
