### ISSUE TITLE
Is it possible to do validation on blur?

### ISSUE THREAD

**Issue by hagcin** [semisleep/simple-vue-validator#15]
Is it possible to do validation on blur? 

Seems like like it is a better user experience to validate on blur than as the user is typing.

**Comment by semisleep** [comment]
Yes, you can use v-model.lazy for field binding (and this is not in the scope of simple-vue-validator):
https://vuejs.org/v2/guide/forms.html#lazy

**Comment by hagcin** [comment]
Thanks!
