### ISSUE TITLE
server post not working after validation success

### ISSUE THREAD

**Issue by tamaghna91** [semisleep/simple-vue-validator#16]
Once validation is successful I was unable to submit my form data through http method,there is no action is happening, should I need to trigger? any help appreciated.
Two screenshots attached for uglifying presentation of my code here

![screenshot from 2017-06-29 17-46-41](https://user-images.githubusercontent.com/8926058/27687109-2a41aef2-5cf3-11e7-9af4-fb9161d98341.png)
![screenshot from 2017-06-29 17-47-18](https://user-images.githubusercontent.com/8926058/27687110-2a435c2a-5cf3-11e7-87aa-e3841620750c.png)

**Comment by tamaghna91** [comment]
my form data like this 

`<form id="responseInput" action="#" @submit.prevent="edit ? updateResponse(response.id) : submit()">
<div class="form-group" :class="{error: validation.hasError('email')}">
			<select v-model="response.category" class="form-control input-lg" name="category">
				<option value="" selected>Select a Category</option>
				<option value="AUTHENTICATION">AUTHENTICATION</option>
				<option value="VALIDATION">VALIDATION</option>
			</select>
		</div>
<button type="submit" v-show="!edit" class="btn btn-primary padding-x bolder uppercase">Submit</button>
			<button type="submit" v-show="edit" class="btn btn-warning padding-x bolder uppercase">Update</button>
</form>`

**Comment by semisleep** [comment]
I don't think this is related to the validator. In the following code:
```
this.$validate().then(function (success) { ... });
```
You are trying to use `this.$http` in the function, but `this` is not binded to the currently Vue instance, so it will fail.

**Comment by tamaghna91** [comment]
Thanks mate, it works with laravel side validation and fetching it's responses.
