### ISSUE TITLE
Integer does not validate that the value is an integer

### ISSUE THREAD

**Issue by kbaney1** [semisleep/simple-vue-validator#17]
If the input has a value of 2.9 or 2.99, etc. parseInt(value) returns 2, so the value is converted to an integer, but it is not validated to make sure the value passed in was an integer.

Rule.prototype.integer = function (message) {
  var value = this._checkValue();
  if (!utils.isEmpty(value)) {
    var number = parseInt(value);
    if (utils.isNaN(number)) {
      this._messages.push(message || this.templates.integer);
    }
// ADD THIS CHECK
    else if (number !== Number(value)) { // 2 !=== 2.9
    this._messages.push(message || this.templates.integer);
  }
  }
  return this;
};

I think the float validator has the same issue.

**Comment by semisleep** [comment]
Code updated, thanks for reporting this bug!
