### ISSUE TITLE
Async validation skipped on double $validate

### ISSUE THREAD

**Issue by sophietk** [semisleep/simple-vue-validator#18]
Hi,

Thanks for your light and terribly efficient plugin.
There is just one problem I faced with it: the validation seems to be forced to success, when validating multiple times, whereas an async validator fails.

Example:
- go to http://simple-vue-validator.maijin.info/#async_validation
- type a domain
- double-click quickly on "SUBMIT" button

The "Validation succeeded!" message appears, but was not expected.

**Comment by semisleep** [comment]
Thanks for reporting this issue, I've update the code, and this should be fixed now.

**Comment by sophietk** [comment]
Thank @semisleep for your responsiveness, it works like a charm.
