### ISSUE TITLE
Demo form does not work

### ISSUE THREAD

**Issue by voroncv** [semisleep/simple-vue-validator#19]
Demo form - http://simple-vue-validator.maijin.info/#dynamic_form not working, please fix.

**Comment by semisleep** [comment]
Just tested and can't see any problem, why do you think it's not working?

**Comment by voroncv** [comment]
Submit function does not return success if all fields are filled

**Comment by semisleep** [comment]
Fixed, thanks for bringing this up!

**Comment by voroncv** [comment]
Can you upload demo this form http://simple-vue-validator.maijin.info/#dynamic_form please
