### ISSUE TITLE
Validate by props, not data

### ISSUE THREAD

**Issue by voroncv** [semisleep/simple-vue-validator#20]
I have props newTax, how i can validate form by this props?
![2017-07-15 15 02 34](https://user-images.githubusercontent.com/20584352/28239194-dfd42c68-696e-11e7-9c16-f4fdd2ea243f.png)

**Comment by semisleep** [comment]
You can pass the 'newTax' to the validator, for example
```
validators: {
   'name, newTax' (name, newTax) {
     if (newTax) return Validator.value(name).required();
   }
   ...
}
```

**Comment by semisleep** [comment]
Also please have a check on this:
http://simple-vue-validator.maijin.info/#cross_field_validation
