### ISSUE TITLE
How do I validate models that is an array?

### ISSUE THREAD

**Issue by jayGorio** [semisleep/simple-vue-validator#23]
Im using the vue onsen framework and started to implement simple vue validator. Here is my code

        <v-ons-list modifier="inset">
		<v-ons-list-item
			modifier="longdivider"
			:name="'question-' + $indexParent"
			v-for="(choice, key, $index) in questionnaire['doc']['choices']"
			:key="key" 
			tappable
		>
						
		<label class="left">
			<v-ons-radio								
			      :input-id="$indexParent + '-' + $index"
			      :value="key"
				v-model="chosenAnswers[$indexParent]"
			>	
			</v-ons-radio>
		</label>

		<label class="center" :for="$indexParent + '-' + $index">
			{{key}}.{{choice}}
		</label>	
		</v-ons-list-item>

		<div class="message">{{ validation.firstError('chosenAnswers') }}</div>
					
		</v-ons-list>

**Comment by shadiqur** [comment]
Got the same problem here.

**Comment by semisleep** [comment]
You can use validator.custom() and write your own validation code there:
http://simple-vue-validator.maijin.info/#custom_rule
