### ISSUE TITLE
float() validator passes value as long as first character is number

### ISSUE THREAD

**Issue by akhchan99** [semisleep/simple-vue-validator#24]
using the float() validator

it'll pass
1 -> ok
1.3 -> ok
1a -> NOT OK
1bdef -> NOT OK
1 2 3 -> NOT OK

it'll fail
a -> ok

**Comment by semisleep** [comment]
Thanks for your feedback, and sorry for the late update.
Just updated the code, and I believe this is fixed.

**Comment by bdsoha** [comment]
Still seems to be a problem:

`v => Validator.value(v).required().float()` is passing even when `v='0a'`.
