### ISSUE TITLE
How to remove dynamic validation 

### ISSUE THREAD

**Issue by keyurptl** [semisleep/simple-vue-validator#25]
Thanks for such great library.  
I want to know I have added validation on one field based on value of other field.  validation is added perfectly. Now how can i remove that validation rule when dependent field value going to be changed. 
My requirement is if one field contains some value at that time other field is required and for some value I don't want that field is required.

**Comment by semisleep** [comment]
Isn't your case covered in the [document](http://simple-vue-validator.maijin.info) here? (please check the "Conditional validation" section)

**Comment by keyurptl** [comment]
Thanks for that it is solved.

**Comment by keyurptl** [comment]
But now after success validation it not submit my form. below is the code for my form submit. 
createUser : function(){
			  this.$validate()
			 .then(function (success) {
				if (success) { 
				alert('Validation succeeded!');
					axios.post('/user/create',this.formData)
					.then(response => {
					
					});
				}
			});
		
		}
It alert but ajax call is not going if I remove this validation then it works.

**Comment by semisleep** [comment]
If it can show the alert then I don't think it has anything to do with the validator. You will need to debug your code to find out what the problem is.

**Comment by keyurptl** [comment]
Thanks for response I got the solution. Issues with function scope. inside then Not able to access form data object, So I write function something like.

createUser : function(){
			this.$validate()
			.then((success) => {
				if(success)
				{
                         }
        });
});

I mean with arrow operator. 
Thanks for such good validator plugin.
