### ISSUE TITLE
Can I user with <script>?

### ISSUE THREAD

**Issue by haeyon098** [semisleep/simple-vue-validator#26]
Hi.
I really wanna use `simple-vue-validator` in my project. But, I don't use `NPM`.
So, can I user with `<script src="(cdn/unpkg address)"></script>`?
If I use `simple-vue-validator`, should I use `NPM`?

**Comment by semisleep** [comment]
Yes, in that case, you can set script tag's "src" to /libs/plugin.js, or install simple-vue-validator through bower.
