### ISSUE TITLE
_checkValue method on rule.js assumes value is required.

### ISSUE THREAD

**Issue by kb-coder** [semisleep/simple-vue-validator#27]
We are trying to validate the maxLength on a text field that is optional. Sometimes it can be null or empty. However, we get an error message thrown from the this._checkValue that states Validator.value not set.

This messes with our unit tests because an error is thrown.

`Rule.prototype._checkValue = function() {
  if (this._value === undefined) {
    throw new Error('Validator.value not set'); // this is the message
  }
  return this._value;
};`

We would prefer if the validation didn't make the assumption that a field is required. So, the following rule for maxLength would make sense:

`Rule.prototype.maxLength = function (length, message) {
  var value = this._checkValue(); // change this to this._value - especially since the next line is checking for null or undefined or empty any way.
  if (!utils.isEmpty(value)) {
    var string = String(value);
    if (string.length > length) {
      this._messages.push(message || utils.format(this.templates.maxLength, length));
    }
  }
  return this;
};`

**Comment by semisleep** [comment]
The incentive of the `_checkValue` method is to ensure that `Validator.value()` method is always called. If `_checkValue` is removed and you forgot to call `Validator.value()` in your code, all optional rules will be skipped, and it's hard to know what went wrong.

You said that the value can be null or empty, but this is totally fine, as `_checkValue` is only checking for `undefined`. Is it possible that your test code failed to call `Validator.value()` in the first place?

**Comment by kb-coder** [comment]
Thanks for responding. I ended up converting to a customer validator instead.
