### ISSUE TITLE
call '$ validate' and check the VueComponent in 'then' block, it prints undefined

### ISSUE THREAD

**Issue by Parkseokje** [semisleep/simple-vue-validator#28]
`
    onSubmit () {
      const $this = this

      this.$validate()
        .then(function (success) {
          if (success) {
            if (confirm('Will you save?')) {
              console.log(this, $this) // output

              $this.createUser($this.form)
              $this.hideModal()
            }
          } else {
            alert('It's not valid')
          }
        })
    },

// output : **undefined, VueComponent { ...**
`

**Comment by semisleep** [comment]
This is not a problem of simple-vue-validator.
If you want to use `this` as the current vue component, try using arrow function or calling .bind(this):
```
.then (success => {...})
```
```
.then (function (success).bind(this))
```
