### ISSUE TITLE
Reset doesn't work correctly

### ISSUE THREAD

**Issue by svojatom** [semisleep/simple-vue-validator#29]
Hello, when I have
```
requiredField: function(val) {
        if (typeof val === 'undefined') {
            val = '';
        }

        return Validator.value(val).required();
    },
```

```
 validators: {
       'newTask.name': {
            debounce: 200,
            validator: Validator.requiredField,
       },
       newTask.due_date': Validator.dateSimple,
},
```
I am not able to reset field `newTask.name` by calling `this.validation.reset();`. But when I change to
```
validators: {
            'newTask.name': Validator.requiredField,
            'newTask.due_date': Validator.dateSimple,
        },
```

everyhing works fine.

**Comment by semisleep** [comment]
Sorry for the late reply.

But I don't think it's related to option object or the debounce field, please check the **Debouncing & caching** section of the doc: http://simple-vue-validator.maijin.info/#async_validation
The "reset" button there works just fine. Can you provide the source code that can reproduce this issue?

Thanks.
