### ISSUE TITLE
Requires complete lodash package

### ISSUE THREAD

**Issue by airyboy** [semisleep/simple-vue-validator#3]
Now it compiles with the complete lodash package (540 kB), that is, from my point of view, is unnecessary.

**Comment by semisleep** [comment]
Hmmm... May be I can build a custom version of lodash which only contains the methods used by this library... Do you include the plugin.js directly, or use this library via npm and webpack?

**Comment by airyboy** [comment]
I use webpack and by the way I already forked your project and altered it in this part by cherry-picking the  lodash methods used in the project. Now I need to test it a bit and I'll make a PR to your repo shortly.

**Comment by semisleep** [comment]
Great to hear that! Thanks!

**Comment by semisleep** [comment]
PR merged.
