### ISSUE TITLE
Is there a way to change the mode per component or field?

### ISSUE THREAD

**Issue by hamzehdoostie** [semisleep/simple-vue-validator#48]
Hello,

Regarding `mode`, I saw from the docs that you can set it two ways:
`Vue.use(SimpleVueValidator, {mode: 'manual'};`
`SimpleVueValidator.setMode('conservative');`

Is there a way to set it to a specific mode, but only within the scope of a component, and not globally?
Also can an individual field be configured to have a specific `mode`?
Thanks.

**Comment by semisleep** [comment]
Sorry, setting interaction mode per component is not supported at this moment. And I don't think I will be able to implement this recently :(
You are welcome to make a pull request for this, if you have time to work on it.

**Comment by hamzehdoostie** [comment]
Thanks for the response, I still love this plugin :]
