### ISSUE TITLE
reset方法触发了change事件导致要两次reset才能真正reset

### ISSUE THREAD

**Issue by Cheneytt** [semisleep/simple-vue-validator#5]
问题描述:
1. 在某个input框中随便输入内容
![image](https://cloud.githubusercontent.com/assets/18325579/22735590/5715a0fa-ee35-11e6-96c1-79a79f0d1662.png)
2. 点reset, 会再次触发required校验
![image](https://cloud.githubusercontent.com/assets/18325579/22735646/958227be-ee35-11e6-8ac9-c5aca9c45e70.png)
3. 再次点击reset, 才可以真正reset掉
![image](https://cloud.githubusercontent.com/assets/18325579/22735660/b3b65534-ee35-11e6-96c6-c9087a3c9402.png)
期望：
点击一次reset就如图3所示

**Comment by semisleep** [comment]
Fix了，谢谢反馈!
