### ISSUE TITLE
[Feature Request] Customized error messages for default validators

### ISSUE THREAD

**Issue by brwr** [semisleep/simple-vue-validator#8]
Hey, again! 😄 

I was looking through the docs again and couldn't find anything on customizing the error messages for the default validators like `.required()` and `.email()`. There is `Validator.extendTemplates()`, but I get the impression that that makes the changes globally. I'm looking to make changes to the error messages on a per-component and per-field basis. Using a custom validator gets the job done, but it's very verbose. See the screenshot below for an example.

![screenshot 2017-02-09 10 30 27](https://cloud.githubusercontent.com/assets/4095660/22797400/f14ba1ba-eeb2-11e6-972e-e3d295cc7a77.png)

Notice how most of the code is just replicating `.required()` and `.email()`.

What do you think? I'm picturing adding an `errors` key (or similar) to the component, the same way we add the `validators` key. Here is a per-field example:

```javascript
export default {
  name: 'component',

  errors: {
    'object.property1.email': 'That doesn\'t look like a valid email address.',
    'object.property1.required': 'We really need you to enter your email.',
    'object.property2.required': 'Yeah. We need this one too.',
  },

  validators: {
    'object.property1': function (value) {
      return Validator.value(value).required().email();
    },

    'object.property2': function (value) {
      return Validator.value(value).required();
    },
  },
};
```

Notice how each key in `errors` is prefixed by the field name. In the case where you want to change the error message on a per-component basis, just leave off the field name. Example:

```javascript
export default {
  name: 'component',

  errors: {
    'required': 'We need you to fill out this field.',
    'object.property1.email': 'That doesn\'t look like a valid email address.',
  },

  validators: {
    'object.property1': function (value) {
      return Validator.value(value).required().email();
    },

    'object.property2': function (value) {
      return Validator.value(value).required();
    },
  },
};
```

Thoughts?

**Comment by semisleep** [comment]
Hey,

The solution you proposed looks good!
I'm thinking maybe for field based validation message, we just put the error message as the last parameter of the validator method, for example:
```javascript
'object.property1': function (value) {
  return Validator.value(value)
    .required('We need you to fill out this field.')
    .email('That doesn\'t look like a valid email address.');
  },
```
That way we don't need to duplicate property key (e.g. `object.property1`) in the code, and therefore reduce the chance of problems caused by typos, also makes it easier to maintain the codes as specific validation logic and messages are tight together, for example, if you delete the `required` rule, you can be sure that `We need you to fill out this field.` is also gone without worry that unused error message is left in the code.

What do you think?

**Comment by semisleep** [comment]
For component based error messages, I think your way of using the same name as validation role is quite great, and I would also update error keys in `templates.js`, so that component base and global error messages all have the same key.

**Comment by brwr** [comment]
Passing the error message as a parameter to .required() and .email() sounds
like a great idea!

**Comment by semisleep** [comment]
Cool! I will work on this a few days later, as I'm completing a project right now.
I hope this won't be a blocker for you :)

**Comment by semisleep** [comment]
@brwr I've implemented this new feature, for detail usages, you can checkout the documentation here: http://simple-vue-validator.maijin.info/#custom_error_message

Please let me know if you have any problem integrating with these new changes, thanks.

**Comment by luxueyan** [comment]
Nice! It help me!
